#spring.application.name=gateway-service
#server.port=8888

server:
  port: 8888
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      mvc:
        routes:
          - id: user-service
            uri: lb://USER-SERVICE
            predicates:
              - Path=/users/**
            filters:
              - StripPrefix=1
          - id: inventory-service
            uri: lb://INVENTORY-SERVICE
            predicates:
              - Path=/inventory/**
            filters:
              - StripPrefix=1
          - id: order-service
            uri: lb://ORDER-SERVICE
            predicates:
              - Path=/orders/**
            filters:
              - StripPrefix=1
          - id: payment-service
            uri: lb://PAYMENT-SERVICE
            predicates:
              - Path=/payments/**
            filters:
              - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
